- name: Show Swap and RAM
  debug: msg="ram={{ ansible_memtotal_mb }}, swap={{ ansible_swaptotal_mb }}"

- name: Create swapfile
  shell: "fallocate -l {{ 2 * ansible_memtotal_mb }}MB /swapfile"
  when: "ansible_swaptotal_mb == 0"

- name: Set swapfile perms
  shell: "chmod 600 /swapfile"
  when: "ansible_swaptotal_mb == 0"

- name: Enable swapfile
  shell: "mkswap /swapfile"
  when: "ansible_swaptotal_mb == 0"

- name: Make permanent
  shell: "echo '/swapfile   none    swap    sw    0   0' >> /etc/fstab"
  when: "ansible_swaptotal_mb == 0"

- name: Reboot instance
  command: /sbin/shutdown -r now
  register: swapmem_reboot
  async: 0
  poll: 0
  ignore_errors: true
  when: "ansible_swaptotal_mb == 0"

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=300 connect_timeout=15
  become: false
  when: "ansible_swaptotal_mb == 0 and swapmem_reboot|changed"
